export declare const clearanceStart_url = "https://clearances.wsib.ca/Clearances/eclearance/start";
export declare const clearanceStart_searchFormSelector = "#TOKENSimpleSearchForm";
export declare const clearanceStart_searchFieldSelector = "#simpleAccountNumbersTOKEN";
export declare const clearanceResult_certificateLinkSelector = "#eClearanceWorkspaceTargSubDivFormXX .fancytable a[rel='eClearanceWorkspaceContent'][href^='GCSearchCertDet']";
export declare const clearanceResult_certificateBadStandingSelector = "#eClearanceWorkspaceTargSubDivFormXX .fancytable .badstanding";
export declare const clearanceResult_defaultErrorMessage = "Clearance certificate link not found.";
export declare const certificate_tableSelector = "#eClearanceWorkspaceDivForm .fancytable";
export declare const certificateField_contractorLegalTradeName = "Contractor Legal / Trade Name";
export declare const certificateField_contractorAddress = "Contractor Address";
export declare const certificateField_naicsCodes = "Contractor NAICS Code and Code Description";
export declare const certificateField_clearanceCertificateNumber = "Clearance certificate number";
export declare const certificateField_validityPeriod = "Validity period (dd-mmm-yyyy)";
export declare const certificateField_principalLegalTradeName = "Principal Legal / Trade Name";
export declare const certificateField_principalAddress = "Principal Address";
